export const GET_POINTS_ALLROOM_SUCCESS = 'GET_POINTS_ALLROOM_SUCCESS';
export const GET_POINTS_ERROR = 'GET_POINTS_ERROR';
export const GET_ALLROOM_POINTS_IN_PROGRESS = 'GET_ALLROOM_POINTS_IN_PROGRESS';
