export const flatPricePlotConst = {
    GET_POINTS_ALLROOM_SUCCESS: 'GET_POINTS_ALLROOM_SUCCESS',
    GET_POINTS_ERROR: 'GET_POINTS_ERROR',
    GET_ALLROOM_POINTS_IN_PROGRESS: 'GET_ALLROOM_POINTS_IN_PROGRESS'
};