export const GET_POINTS_1ROOM_SUCCESS = 'GET_POINTS_1ROOM_SUCCESS';
export const GET_POINTS_2ROOM_SUCCESS = 'GET_POINTS_2ROOM_SUCCESS';
export const GET_POINTS_3ROOM_SUCCESS = 'GET_POINTS_3ROOM_SUCCESS';
export const GET_POINTS_4ROOM_SUCCESS = 'GET_POINTS_4ROOM_SUCCESS';

export const GET_POINTS_ERROR = 'GET_POINTS_ERROR';
export const GET_1ROOM_POINTS_IN_PROGRESS = 'GET_1ROOM_POINTS_IN_PROGRESS';
export const GET_MULTIROOM_POINTS_IN_PROGRESS = 'GET_1ROOM_POINTS_IN_PROGRESS';