export const flatReadConst = {
    GET_FLAT_SUCCESS: 'GET_FLAT_SUCCESS',
    GET_FLAT_ERROR: 'GET_FLAT_ERROR',
    GET_FLAT_IN_PROGRESS: 'GET_FLAT_IN_PROGRESS',
    SHOW_PHOTOS: 'SHOW_PHOTOS',
    HIDE_PHOTOS: 'HIDE_PHOTOS'
};