export const houseReadConst = {
    GET_HOUSE_SUCCESS: 'GET_HOUSE_SUCCESS',
    GET_HOUSE_ERROR: 'GET_HOUSE_ERROR',
    GET_HOUSE_IN_PROGRESS: 'GET_HOUSE_IN_PROGRESS',
    GET_STATISTICS_SUCCESS: 'GET_STATISTICS_SUCCESS',
    GET_STATISTICS_ERROR: 'GET_STATISTICS_ERROR',
    GET_STATISTICS_IN_PROGRESS: 'GET_STATISTICS_IN_PROGRESS'
};