export const paybackMapConst = {
    GET_POINTS_SUCCESS: 'GET_POINTS_SUCCESS',
    GET_POINTS_ERROR: 'GET_POINTS_ERROR',
    GET_POINTS_IN_PROGRESS: 'GET_POINTS_IN_PROGRESS',
    SET_PAYBACK_LIMIT: 'SET_PAYBACK_LIMIT',
    SET_USE_UPN_DATA: 'SET_USE_UPN_DATA',
    SET_USE_N1_DATA: 'SET_USE_N1_DATA'
};