export const GET_POINTS_SUCCESS = 'GET_POINTS_SUCCESS';
export const GET_POINTS_ERROR = 'GET_POINTS_ERROR';
export const GET_POINTS_IN_PROGRESS = 'GET_POINTS_IN_PROGRESS';
export const SET_PAYBACK_LIMIT = 'SET_PAYBACK_LIMIT';