export const flatsSearchBarConst = {
    SET_SHOW_ARCHIVED: 'SET_SHOW_ARCHIVED',
    SET_EXCLUDE_FIRST_FLOOR: 'SET_EXCLUDE_FIRST_FLOOR',
    SET_EXCLUDE_LAST_FLOOR: 'SET_EXCLUDE_LAST_FLOOR',
    SET_MIN_PRICE: 'SET_MIN_PRICE',
    SET_MAX_PRICE: 'SET_MAX_PRICE',
    SET_MIN_BUILD_YEAR: 'SET_MIN_BUILD_YEAR',
    SET_MAX_SUBWAY_DISTANCE: 'SET_MAX_SUBWAY_DISTANCE',
    SET_CLOSEST_SUBWAY_STATION_ID: 'SET_CLOSEST_SUBWAY_STATION_ID',
    SET_ADDRESS_PART: 'SET_ADDRESS_PART',
    SET_SHOW_ROOMS: 'SET_SHOW_ROOMS',
    SET_START_DATE: 'SET_START_DATE',
    SET_END_DATE: 'SET_END_DATE',
    CLEAR_SEARCH_PARAMETERS: 'CLEAR_SEARCH_PARAMETERS'
};